### ISSUE TITLE
Typo in kernel command line? 

### ISSUE THREAD

**Issue by GeoZac** [xiaomi-sm6250-devs/android_device_xiaomi_miatoll#1]
The argument 
`console=ttyMSM0,115200,n8` in 
https://github.com/xiaomi-sm6250-devs/android_device_xiaomi_curtana-unified/blob/03121bc78864c15367960f12ec84819a0116280a/BoardConfig.mk#L63
seems to be typo/
Stock boot image command line has  
`console=ttyMSM0,115200n8` 
[Source](https://git.rip/dumps/redmi/curtana/-/blob/qssi-user-10-QKQ1.191215.002-V12.0.1.0.QJWINXM-release-keys/bootimg/img_info#L12)

**Comment by erfanoabdi** [comment]
yeah you're right but this kernel console is unused at all
